---
title: "Mental data"
output:
  html_document:
    code_folding: show
    highlight: textmate
    df_print: paged
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

############################################################
# Section 5.1: Mental health data
# This script reproduces the numerical results for Tables 5--7.
############################################################

```{r message=FALSE, include=FALSE}
library(ordinal)
library(VGAM)
library(CUB)
library(tidyverse)
library(Rmpfr)
library(zipfR)
library(hypergeo)
library(extraDistr)
library(MASS)
library(haven)
library(DEoptim)
library(lubridate)
library(mgcv)
library(future)
library(doFuture)
library(foreach)
library(progressr)

# Source functions
source(file.path("code", "common_functions.R"))
```

```{r}
# Load Data
library(cgam)
data(mental)
head(mental)
```

```{r}
# response y
table(mental$mental)
mental$mental = factor(mental$mental, levels = c(
  "1", 
  "2", 
  "3",
  "4"
), ordered = TRUE)
```

# Table 5

## Fit cumulative link models and CUB model

## cumulative link models
```{r}
## Logit (POM)
logit_model <- clm(factor(mental) ~ ses + life, data = mental, link = "logit")
## Probit
probit_model <- clm(factor(mental) ~ ses + life, data = mental, link = "probit")
## Complementary log-log
cloglog_model <- clm(factor(mental) ~ ses + life, data = mental, link = "cloglog")

clm_models <- list(
  Logit  = logit_model,
  Probit = probit_model,
  Cloglog = cloglog_model
)

clm_fit_stats <- data.frame(
  Model  = names(clm_models),
  logLik = sapply(clm_models, function(mod) as.numeric(logLik(mod))),
  AIC    = sapply(clm_models, AIC),
  BIC    = sapply(clm_models, BIC)
)

print(clm_fit_stats)

lapply(clm_models, function(mod) coef(summary(mod)))
```

## CUB model
```{r}
# uncertainty : NO covariate
# feeling : YES covariate
cub_model <- GEM(Formula(mental ~ 0|ses+life|0), family="cub", data = mental)
summary(cub_model)
```


# Table 6

## Fit proposed models

```{r}
# 여기서부터 손봐야 함 
# 함수로라도 만들어서 한  번ㅔ 다  돌아가도록 
# 실  제 로  는 표에 넣은 모델 만 돌려서 동일한지 확인 
# 아래 코드로 돌려보기 
# surv_names <- names(surv_candidates)
# rhoj_names <- names(rhoj_candidates)
# 
# # Example:
# # surv_names <- names(surv_candidates)[1:5]
# # rhoj_names <- names(rhoj_candidates)[1:20]
# 
# all_results <- list()
# 
# for (surv_name in surv_names) {
#   for (rhoj_name in rhoj_names) {

X <- model.matrix(~ -1 + ses + life, data = mental)
y <- as.numeric(mental$mental)
m <- max(unique(y))

surv_candidates <- make_surv_func(m = m)
rhoj_candidates <- make_rhoj_candidates()

all_results <- list()

for (surv_name in names(surv_candidates)[1:5]) { # Only Simple baseline Sfs
    for (rhoj_name in names(rhoj_candidates)) {
        
        eta_name <- get_eta_name_for_rhoj(rhoj_name)
        
        surv_info <- surv_candidates[[surv_name]]
        eta_info  <- geta_candidates[[eta_name]]
        rhoj_info <- rhoj_candidates[[rhoj_name]]
        
        init_fit <- get_data_driven_init(
            y = y, m = m,
            surv_info = surv_info,
            eta_info  = eta_info,
            rhoj_info = rhoj_info
        )
        
        # overwrite initial values by data-driven initial values
        surv_info$init <- init_fit$surv_init
        rhoj_info$init <- init_fit$rhoj_init
        
        fit <- fit_one_combo(
            X = X, y = y, m = m, n = nrow(X),
            surv_info = surv_info,
            eta_info  = eta_info,
            rhoj_info = rhoj_info,
            method = "BFGS"
        )
        
        comb_key <- paste(surv_name, eta_name, rhoj_name, sep = "__")
        
        all_results[[comb_key]] <- c(
            list(
                surv = surv_name,
                geta = eta_name,
                rhoj = rhoj_name
            ),
            fit
        )
        
        cat("Finished:", comb_key, "\n")
    }
}
```

## Find the best fitted model for each transformation function

```{r}
best_BIC_by_rhoa <- select_best_by_rhoa(
  all_results = all_results,
  criterion = "BIC",
  require_convergence = TRUE
)
best_BIC_by_rhoa[, c("rho_a", "surv", "rhoj", "logLik", "AIC", "BIC", "conv", "surv_par", "rhoj_par")]
```


# Table 7

## Estimation results for the final best model

```{r}
final_AIC_row <- best_BIC_by_rhoa[which.min(best_BIC_by_rhoa$AIC), ]
final_BIC_row <- best_BIC_by_rhoa[which.min(best_BIC_by_rhoa$BIC), ]

final_AIC_fit <- all_results[[final_AIC_row$key]]
final_BIC_fit <- all_results[[final_BIC_row$key]]

table_AIC_result <- make_final_table(
  fit = final_AIC_fit,
  X = X,
  criterion = "AIC"
)

table_BIC_result <- make_final_table(
  fit = final_BIC_fit,
  X = X,
  criterion = "BIC"
)

print(final_AIC_row[, c("surv", "rhoj", "logLik", "AIC", "BIC")])
print(table_AIC_result)

print(final_BIC_row[, c("surv", "rhoj", "logLik", "AIC", "BIC")])
print(table_BIC_result)
```

