---
title: "Fine particulate matter data"
output:
  html_document:
    code_folding: show
    highlight: textmate
    df_print: paged
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

############################################################
# Section 5.3: Fine particulate matter data
# This script reproduces the numerical results for Tables 12--14.
############################################################

```{r message=FALSE, include=FALSE}
library(ordinal)
library(VGAM)
library(CUB)
library(tidyverse)

# Source functions
source(file.path("code", "common_functions.R"))
```

```{r}
# Load Data
pm25 = read.csv(file.path("data", "pm25_seoul_sampled.csv"), header = TRUE)
str(pm25)
head(pm25)
```

```{r}
# response y
table(pm25$pm_grade)
pm25$pm_grade = factor(pm25$pm_grade, levels = c(
  "Good", "Moderate", "Bad", "Very_bad"
), ordered = TRUE)

# Standardize continuous covariates
pm25[, c("temp", "humid", "wind", "press")] <- scale(pm25[, c("temp", "humid", "wind", "press")])
```

# Table 12

## Fit cumulative link models

## cumulative link models
```{r}
## Logit (POM)
logit_model <- clm(pm_grade ~ temp+humid+wind+rain+press+season, data = pm25, link = "logit")
## Probit
probit_model <- clm(pm_grade ~ temp+humid+wind+rain+press+season, data = pm25, link = "probit")
## Complementary log-log
cloglog_model <- clm(pm_grade ~ temp+humid+wind+rain+press+season, data = pm25, link = "cloglog")

clm_models <- list(
  Logit  = logit_model,
  Probit = probit_model,
  Cloglog = cloglog_model
)

clm_fit_stats <- data.frame(
  Model  = names(clm_models),
  logLik = sapply(clm_models, function(mod) as.numeric(logLik(mod))),
  AIC    = sapply(clm_models, AIC),
  BIC    = sapply(clm_models, BIC)
)

print(clm_fit_stats)

lapply(clm_models, function(mod) coef(summary(mod)))
```

# Table 13

## Fit proposed models 

```{r}
X <- model.matrix(~ -1 + temp + humid + wind + rain + press + season, data = pm25)
y <- as.integer(pm25$pm_grade)
m <- max(unique(y))

surv_candidates <- make_surv_func(m = m)
rhoj_candidates <- make_rhoj_candidates()

all_results <- list()

for (surv_name in names(surv_candidates)[1:9]) { 
    for (rhoj_name in names(rhoj_candidates)) {
        
        eta_name <- get_eta_name_for_rhoj(rhoj_name)
        
        surv_info <- surv_candidates[[surv_name]]
        eta_info  <- geta_candidates[[eta_name]]
        rhoj_info <- rhoj_candidates[[rhoj_name]]
        
        init_fit <- get_data_driven_init(
            y = y, m = m,
            surv_info = surv_info,
            eta_info  = eta_info,
            rhoj_info = rhoj_info
        )
        
        # overwrite initial values by data-driven initial values
        surv_info$init <- init_fit$surv_init
        rhoj_info$init <- init_fit$rhoj_init
        
        fit <- fit_one_combo(
            X = X, y = y, m = m, n = nrow(X),
            surv_info = surv_info,
            eta_info  = eta_info,
            rhoj_info = rhoj_info,
            method = "BFGS"
        )
        
        comb_key <- paste(surv_name, eta_name, rhoj_name, sep = "__")
        
        all_results[[comb_key]] <- c(
            list(
                surv = surv_name,
                geta = eta_name,
                rhoj = rhoj_name
            ),
            fit
        )
        
        cat("Finished:", comb_key, "\n")
    }
}
```

## Find the best fitted model for each transformation function

```{r}
best_BIC_by_rhoa <- select_best_by_rhoa(
  all_results = all_results,
  criterion = "BIC",
  require_convergence = TRUE
)
best_BIC_by_rhoa[, c("rho_a", "surv", "rhoj", "logLik", "AIC", "BIC", "conv", "surv_par", "rhoj_par")]
```

# Table 14

## Estimation results for the final best model

```{r}
final_AIC_row <- best_BIC_by_rhoa[which.min(best_BIC_by_rhoa$AIC), ]
final_BIC_row <- best_BIC_by_rhoa[which.min(best_BIC_by_rhoa$BIC), ]

final_AIC_fit <- all_results[[final_AIC_row$key]]
final_BIC_fit <- all_results[[final_BIC_row$key]]

table_AIC_result <- make_final_table(
  fit = final_AIC_fit,
  X = X,
  criterion = "AIC"
)

table_BIC_result <- make_final_table(
  fit = final_BIC_fit,
  X = X,
  criterion = "BIC"
)

print(final_AIC_row[, c("surv", "rhoj", "logLik", "AIC", "BIC")])
print(table_AIC_result)

print(final_BIC_row[, c("surv", "rhoj", "logLik", "AIC", "BIC")])
print(table_BIC_result)
```

